export const COUNTRY_CODES_NEW = [
    {
        name: 'Saudi Arabia',
        name_ar: 'المملكة العربية السعودية',
        flag: require('../../assets/flags/sa.png'),
        alpha2Code: 'SA',
        callingCode: '966',
        FIELD6: null,
    },
    {
        name: 'United Arab Emirates',
        name_ar: 'الإمارات العربية المتحدة',
        flag: require('../../assets/flags/ae.png'),
        alpha2Code: 'AE',
        callingCode: '971',
        FIELD6: null,
    },
    {
        name: 'Afghanistan',
        name_ar: 'أفغانستان',
        flag: require('../../assets/flags/af.png'),
        alpha2Code: 'AF',
        callingCode: '93',
        FIELD6: null,
    },
    {
        name: 'Albania',
        name_ar: 'ألبانيا',
        flag: require('../../assets/flags/al.png'),
        alpha2Code: 'AL',
        callingCode: '355',
        FIELD6: null,
    },
    {
        name: 'Algeria',
        name_ar: 'الجزائر',
        flag: require('../../assets/flags/dz.png'),
        alpha2Code: 'DZ',
        callingCode: '213',
        FIELD6: null,
    },
    {
        name: 'American Samoa',
        name_ar: 'ساموا الأمريكية',
        flag: require('../../assets/flags/as.png'),
        alpha2Code: 'AS',
        callingCode: '1684',
        FIELD6: null,
    },
    {
        name: 'Andorra',
        name_ar: 'أندورا',
        flag: require('../../assets/flags/ad.png'),
        alpha2Code: 'AD',
        callingCode: '376',
        FIELD6: null,
    },
    {
        name: 'Angola',
        name_ar: 'أنغولا',
        flag: require('../../assets/flags/ao.png'),
        alpha2Code: 'AO',
        callingCode: '244',
        FIELD6: null,
    },
    {
        name: 'Anguilla',
        name_ar: 'أنغيلا',
        flag: require('../../assets/flags/ai.png'),
        alpha2Code: 'AI',
        callingCode: '1264',
        FIELD6: null,
    },
    {
        name: 'Antarctica',
        name_ar: 'القارة القطبية الجنوبية',
        flag: require('../../assets/flags/aq.png'),
        alpha2Code: 'AQ',
        callingCode: '672',
        FIELD6: null,
    },
    {
        name: 'Antigua and Barbuda',
        name_ar: 'أنتيغوا وبربودا',
        flag: require('../../assets/flags/ag.png'),
        alpha2Code: 'AG',
        callingCode: '1268',
        FIELD6: null,
    },
    {
        name: 'Argentina',
        name_ar: 'الأرجنتين',
        flag: require('../../assets/flags/ar.png'),
        alpha2Code: 'AR',
        callingCode: '54',
        FIELD6: null,
    },
    {
        name: 'Armenia',
        name_ar: 'أرمينيا',
        flag: require('../../assets/flags/am.png'),
        alpha2Code: 'AM',
        callingCode: '374',
        FIELD6: null,
    },
    {
        name: 'Aruba',
        name_ar: 'أروبا',
        flag: require('../../assets/flags/aw.png'),
        alpha2Code: 'AW',
        callingCode: '297',
        FIELD6: null,
    },
    {
        name: 'Australia',
        name_ar: 'أستراليا',
        flag: require('../../assets/flags/au.png'),
        alpha2Code: 'AU',
        callingCode: '61',
        FIELD6: null,
    },
    {
        name: 'Austria',
        name_ar: 'النمسا',
        flag: require('../../assets/flags/at.png'),
        alpha2Code: 'AT',
        callingCode: '43',
        FIELD6: null,
    },
    {
        name: 'Azerbaijan',
        name_ar: 'أذربيجان',
        flag: require('../../assets/flags/az.png'),
        alpha2Code: 'AZ',
        callingCode: '994',
        FIELD6: null,
    },
    {
        name: 'Bahamas',
        name_ar: 'الباهاما',
        flag: require('../../assets/flags/bs.png'),
        alpha2Code: 'BS',
        callingCode: '1242',
        FIELD6: null,
    },
    {
        name: 'Bahrain',
        name_ar: 'البحرين',
        flag: require('../../assets/flags/bh.png'),
        alpha2Code: 'BH',
        callingCode: '973',
        FIELD6: null,
    },
    {
        name: 'Bangladesh',
        name_ar: 'بنغلاديش',
        flag: require('../../assets/flags/bd.png'),
        alpha2Code: 'BD',
        callingCode: '880',
        FIELD6: null,
    },
    {
        name: 'Barbados',
        name_ar: 'بربادوس',
        flag: require('../../assets/flags/bb.png'),
        alpha2Code: 'BB',
        callingCode: '1246',
        FIELD6: null,
    },
    {
        name: 'Belarus',
        name_ar: 'روسيا البيضاء',
        flag: require('../../assets/flags/by.png'),
        alpha2Code: 'BY',
        callingCode: '375',
        FIELD6: null,
    },
    {
        name: 'Belgium',
        name_ar: 'بلجيكا',
        flag: require('../../assets/flags/be.png'),
        alpha2Code: 'BE',
        callingCode: '32',
        FIELD6: null,
    },
    {
        name: 'Belize',
        name_ar: 'بليز',
        flag: require('../../assets/flags/bz.png'),
        alpha2Code: 'BZ',
        callingCode: '501',
        FIELD6: null,
    },
    {
        name: 'Benin',
        name_ar: 'بنين',
        flag: require('../../assets/flags/bj.png'),
        alpha2Code: 'BJ',
        callingCode: '229',
        FIELD6: null,
    },
    {
        name: 'Bermuda',
        name_ar: 'برمودا',
        flag: require('../../assets/flags/bm.png'),
        alpha2Code: 'BM',
        callingCode: '1441',
        FIELD6: null,
    },
    {
        name: 'Bhutan',
        name_ar: 'بوتان',
        flag: require('../../assets/flags/bt.png'),
        alpha2Code: 'BT',
        callingCode: '975',
        FIELD6: null,
    },
    {
        name: 'Bolivia (Plurinational State of)',
        name_ar: 'بوليفيا (دولة متعددة القوميات)',
        flag: require('../../assets/flags/bo.png'),
        alpha2Code: 'BO',
        callingCode: '591',
        FIELD6: null,
    },
    {
        name: 'Bonaire',
        name_ar: 'بونير',
        flag: require('../../assets/flags/bq.png'),
        alpha2Code: 'BQ',
        callingCode: '5997',
        FIELD6: 5997,
    },
    {
        name: 'Bosnia and Herzegovina',
        name_ar: 'البوسنة والهرسك',
        flag: require('../../assets/flags/ba.png'),
        alpha2Code: 'BA',
        callingCode: '387',
        FIELD6: null,
    },
    {
        name: 'Botswana',
        name_ar: 'بوتسوانا',
        flag: require('../../assets/flags/bw.png'),
        alpha2Code: 'BW',
        callingCode: '267',
        FIELD6: null,
    },
    {
        name: 'Brazil',
        name_ar: 'البرازيل',
        flag: require('../../assets/flags/br.png'),
        alpha2Code: 'BR',
        callingCode: '55',
        FIELD6: null,
    },
    {
        name: 'British Indian Ocean Territory',
        name_ar: 'إقليم المحيط البريطاني الهندي',
        flag: require('../../assets/flags/io.png'),
        alpha2Code: 'IO',
        callingCode: '246',
        FIELD6: null,
    },
    {
        name: 'Brunei Darussalam',
        name_ar: 'بروناي دار السلام',
        flag: require('../../assets/flags/bn.png'),
        alpha2Code: 'BN',
        callingCode: '673',
        FIELD6: null,
    },
    {
        name: 'Bulgaria',
        name_ar: 'بلغاريا',
        flag: require('../../assets/flags/bg.png'),
        alpha2Code: 'BG',
        callingCode: '359',
        FIELD6: null,
    },
    {
        name: 'Burkina Faso',
        name_ar: 'بوركينا فاسو',
        flag: require('../../assets/flags/bf.png'),
        alpha2Code: 'BF',
        callingCode: '226',
        FIELD6: null,
    },
    {
        name: 'Burundi',
        name_ar: 'بوروندي',
        flag: require('../../assets/flags/bi.png'),
        alpha2Code: 'BI',
        callingCode: '257',
        FIELD6: null,
    },
    {
        name: 'Cabo Verde',
        name_ar: 'كابو فيردي',
        flag: require('../../assets/flags/cv.png'),
        alpha2Code: 'CV',
        callingCode: '238',
        FIELD6: null,
    },
    {
        name: 'Cambodia',
        name_ar: 'كمبوديا',
        flag: require('../../assets/flags/kh.png'),
        alpha2Code: 'KH',
        callingCode: '855',
        FIELD6: null,
    },
    {
        name: 'Cameroon',
        name_ar: 'الكاميرون',
        flag: require('../../assets/flags/cm.png'),
        alpha2Code: 'CM',
        callingCode: '237',
        FIELD6: null,
    },
    {
        name: 'Canada',
        name_ar: 'كندا',
        flag: require('../../assets/flags/ca.png'),
        alpha2Code: 'CA',
        callingCode: '1',
        FIELD6: null,
    },
    {
        name: 'Cayman Islands',
        name_ar: 'جزر كايمان',
        flag: require('../../assets/flags/ky.png'),
        alpha2Code: 'KY',
        callingCode: '1345',
        FIELD6: null,
    },
    {
        name: 'Central African Republic',
        name_ar: 'جمهورية افريقيا الوسطى',
        flag: require('../../assets/flags/cf.png'),
        alpha2Code: 'CF',
        callingCode: '236',
        FIELD6: null,
    },
    {
        name: 'Chad',
        name_ar: 'تشاد',
        flag: require('../../assets/flags/td.png'),
        alpha2Code: 'TD',
        callingCode: '235',
        FIELD6: null,
    },
    {
        name: 'Chile',
        name_ar: 'تشيلي',
        flag: require('../../assets/flags/cl.png'),
        alpha2Code: 'CL',
        callingCode: '56',
        FIELD6: null,
    },
    {
        name: 'China',
        name_ar: 'الصين',
        flag: require('../../assets/flags/cn.png'),
        alpha2Code: 'CN',
        callingCode: '86',
        FIELD6: null,
    },
    {
        name: 'Christmas Island',
        name_ar: 'جزيرة الكريسماس',
        flag: require('../../assets/flags/cx.png'),
        alpha2Code: 'CX',
        callingCode: '61',
        FIELD6: null,
    },
    {
        name: 'Cocos (Keeling) Islands',
        name_ar: 'جزر كوكوس',
        flag: require('../../assets/flags/cc.png'),
        alpha2Code: 'CC',
        callingCode: '61',
        FIELD6: null,
    },
    {
        name: 'Colombia',
        name_ar: 'كولومبيا',
        flag: require('../../assets/flags/co.png'),
        alpha2Code: 'CO',
        callingCode: '57',
        FIELD6: null,
    },
    {
        name: 'Comoros',
        name_ar: 'جزر القمر',
        flag: require('../../assets/flags/km.png'),
        alpha2Code: 'KM',
        callingCode: '269',
        FIELD6: null,
    },
    {
        name: 'Congo',
        name_ar: 'الكونغو',
        flag: require('../../assets/flags/cg.png'),
        alpha2Code: 'CG',
        callingCode: '242',
        FIELD6: null,
    },
    {
        name: 'Congo (Democratic Republic of the)',
        name_ar: 'الكونغو (جمهورية الكونغو الديمقراطية و)',
        flag: require('../../assets/flags/cd.png'),
        alpha2Code: 'CD',
        callingCode: '243',
        FIELD6: null,
    },
    {
        name: 'Cook Islands',
        name_ar: 'جزر كوك',
        flag: require('../../assets/flags/ck.png'),
        alpha2Code: 'CK',
        callingCode: '682',
        FIELD6: null,
    },
    {
        name: 'Costa Rica',
        name_ar: 'كوستا ريكا',
        flag: require('../../assets/flags/cr.png'),
        alpha2Code: 'CR',
        callingCode: '506',
        FIELD6: null,
    },
    {
        name: 'Croatia',
        name_ar: 'كرواتيا',
        flag: require('../../assets/flags/hr.png'),
        alpha2Code: 'HR',
        callingCode: '385',
        FIELD6: null,
    },
    {
        name: 'Cuba',
        name_ar: 'كوبا',
        flag: require('../../assets/flags/cu.png'),
        alpha2Code: 'CU',
        callingCode: '53',
        FIELD6: null,
    },
    {
        name: 'Curaçao',
        name_ar: 'كوراساو',
        flag: require('../../assets/flags/cw.png'),
        alpha2Code: 'CW',
        callingCode: '599',
        FIELD6: null,
    },
    {
        name: 'Cyprus',
        name_ar: 'قبرص',
        flag: require('../../assets/flags/cy.png'),
        alpha2Code: 'CY',
        callingCode: '357',
        FIELD6: null,
    },
    {
        name: 'Czech Republic',
        name_ar: 'جمهورية التشيك',
        flag: require('../../assets/flags/cz.png'),
        alpha2Code: 'CZ',
        callingCode: '420',
        FIELD6: null,
    },
    {
        name: "Côte d'Ivoire",
        name_ar: 'كوت ديفوار',
        flag: require('../../assets/flags/ci.png'),
        alpha2Code: 'CI',
        callingCode: '225',
        FIELD6: null,
    },
    {
        name: 'Denmark',
        name_ar: 'الدنمارك',
        flag: require('../../assets/flags/dk.png'),
        alpha2Code: 'DK',
        callingCode: '45',
        FIELD6: null,
    },
    {
        name: 'Djibouti',
        name_ar: 'جيبوتي',
        flag: require('../../assets/flags/dj.png'),
        alpha2Code: 'DJ',
        callingCode: '253',
        FIELD6: null,
    },
    {
        name: 'Dominica',
        name_ar: 'دومينيكا',
        flag: require('../../assets/flags/dm.png'),
        alpha2Code: 'DM',
        callingCode: '1767',
        FIELD6: null,
    },
    {
        name: 'Dominican Republic',
        name_ar: 'جمهورية الدومنيكان',
        flag: require('../../assets/flags/do.png'),
        alpha2Code: 'DO',
        callingCode: '1809',
        FIELD6: null,
    },
    {
        name: 'Ecuador',
        name_ar: 'الإكوادور',
        flag: require('../../assets/flags/ec.png'),
        alpha2Code: 'EC',
        callingCode: '593',
        FIELD6: null,
    },
    {
        name: 'Egypt',
        name_ar: 'مصر',
        flag: require('../../assets/flags/eg.png'),
        alpha2Code: 'EG',
        callingCode: '20',
        FIELD6: null,
    },
    {
        name: 'El Salvador',
        name_ar: 'السلفادور',
        flag: require('../../assets/flags/sv.png'),
        alpha2Code: 'SV',
        callingCode: '503',
        FIELD6: null,
    },
    {
        name: 'Equatorial Guinea',
        name_ar: 'غينيا الإستوائية',
        flag: require('../../assets/flags/gq.png'),
        alpha2Code: 'GQ',
        callingCode: '240',
        FIELD6: null,
    },
    {
        name: 'Eritrea',
        name_ar: 'إريتريا',
        flag: require('../../assets/flags/er.png'),
        alpha2Code: 'ER',
        callingCode: '291',
        FIELD6: null,
    },
    {
        name: 'Estonia',
        name_ar: 'استونيا',
        flag: require('../../assets/flags/ee.png'),
        alpha2Code: 'EE',
        callingCode: '372',
        FIELD6: null,
    },
    {
        name: 'Ethiopia',
        name_ar: 'أثيوبيا',
        flag: require('../../assets/flags/et.png'),
        alpha2Code: 'ET',
        callingCode: '251',
        FIELD6: null,
    },
    {
        name: 'Falkland Islands (Malvinas)',
        name_ar: 'جزر فوكلاند (مالفيناس)',
        flag: require('../../assets/flags/fk.png'),
        alpha2Code: 'FK',
        callingCode: '500',
        FIELD6: null,
    },
    {
        name: 'Faroe Islands',
        name_ar: 'جزر فاروس',
        flag: require('../../assets/flags/fo.png'),
        alpha2Code: 'FO',
        callingCode: '298',
        FIELD6: null,
    },
    {
        name: 'Fiji',
        name_ar: 'فيجي',
        flag: require('../../assets/flags/fj.png'),
        alpha2Code: 'FJ',
        callingCode: '679',
        FIELD6: null,
    },
    {
        name: 'Finland',
        name_ar: 'فنلندا',
        flag: require('../../assets/flags/fi.png'),
        alpha2Code: 'FI',
        callingCode: '358',
        FIELD6: null,
    },
    {
        name: 'France',
        name_ar: 'فرنسا',
        flag: require('../../assets/flags/fr.png'),
        alpha2Code: 'FR',
        callingCode: '33',
        FIELD6: null,
    },
    {
        name: 'French Guiana',
        name_ar: 'غيانا الفرنسية',
        flag: require('../../assets/flags/gf.png'),
        alpha2Code: 'GF',
        callingCode: '594',
        FIELD6: null,
    },
    {
        name: 'French Polynesia',
        name_ar: 'بولينيزيا الفرنسية',
        flag: require('../../assets/flags/pf.png'),
        alpha2Code: 'PF',
        callingCode: '689',
        FIELD6: null,
    },
    {
        name: 'Gabon',
        name_ar: 'الغابون',
        flag: require('../../assets/flags/ga.png'),
        alpha2Code: 'GA',
        callingCode: '241',
        FIELD6: null,
    },
    {
        name: 'Gambia',
        name_ar: 'غامبيا',
        flag: require('../../assets/flags/gm.png'),
        alpha2Code: 'GM',
        callingCode: '220',
        FIELD6: null,
    },
    {
        name: 'Georgia',
        name_ar: 'جورجيا',
        flag: require('../../assets/flags/ge.png'),
        alpha2Code: 'GE',
        callingCode: '995',
        FIELD6: null,
    },
    {
        name: 'Germany',
        name_ar: 'ألمانيا',
        flag: require('../../assets/flags/de.png'),
        alpha2Code: 'DE',
        callingCode: '49',
        FIELD6: null,
    },
    {
        name: 'Ghana',
        name_ar: 'غانا',
        flag: require('../../assets/flags/gh.png'),
        alpha2Code: 'GH',
        callingCode: '233',
        FIELD6: null,
    },
    {
        name: 'Gibraltar',
        name_ar: 'جبل طارق',
        flag: require('../../assets/flags/gi.png'),
        alpha2Code: 'GI',
        callingCode: '350',
        FIELD6: null,
    },
    {
        name: 'Greece',
        name_ar: 'اليونان',
        flag: require('../../assets/flags/gr.png'),
        alpha2Code: 'GR',
        callingCode: '30',
        FIELD6: null,
    },
    {
        name: 'Greenland',
        name_ar: 'الأرض الخضراء',
        flag: require('../../assets/flags/gl.png'),
        alpha2Code: 'GL',
        callingCode: '299',
        FIELD6: null,
    },
    {
        name: 'Grenada',
        name_ar: 'غرينادا',
        flag: require('../../assets/flags/gd.png'),
        alpha2Code: 'GD',
        callingCode: '1473',
        FIELD6: null,
    },
    {
        name: 'Guadeloupe',
        name_ar: 'جوادلوب',
        flag: require('../../assets/flags/gp.png'),
        alpha2Code: 'GP',
        callingCode: '590',
        FIELD6: null,
    },
    {
        name: 'Guam',
        name_ar: 'غوام',
        flag: require('../../assets/flags/gu.png'),
        alpha2Code: 'GU',
        callingCode: '1671',
        FIELD6: null,
    },
    {
        name: 'Guatemala',
        name_ar: 'غواتيمالا',
        flag: require('../../assets/flags/gt.png'),
        alpha2Code: 'GT',
        callingCode: '502',
        FIELD6: null,
    },
    {
        name: 'Guernsey',
        name_ar: 'غيرنسي',
        flag: require('../../assets/flags/gg.png'),
        alpha2Code: 'GG',
        callingCode: '44',
        FIELD6: null,
    },
    {
        name: 'Guinea',
        name_ar: 'غينيا',
        flag: require('../../assets/flags/gn.png'),
        alpha2Code: 'GN',
        callingCode: '224',
        FIELD6: null,
    },
    {
        name: 'Guinea-Bissau',
        name_ar: 'غينيا بيساو',
        flag: require('../../assets/flags/gw.png'),
        alpha2Code: 'GW',
        callingCode: '245',
        FIELD6: null,
    },
    {
        name: 'Guyana',
        name_ar: 'غيانا',
        flag: require('../../assets/flags/gy.png'),
        alpha2Code: 'GY',
        callingCode: '592',
        FIELD6: null,
    },
    {
        name: 'Haiti',
        name_ar: 'هايتي',
        flag: require('../../assets/flags/ht.png'),
        alpha2Code: 'HT',
        callingCode: '509',
        FIELD6: null,
    },
    {
        name: 'Holy See',
        name_ar: 'الكرسي الرسولي',
        flag: require('../../assets/flags/va.png'),
        alpha2Code: 'VA',
        callingCode: '379',
        FIELD6: null,
    },
    {
        name: 'Honduras',
        name_ar: 'هندوراس',
        flag: require('../../assets/flags/hn.png'),
        alpha2Code: 'HN',
        callingCode: '504',
        FIELD6: null,
    },
    {
        name: 'Hong Kong',
        name_ar: 'هونغ كونغ',
        flag: require('../../assets/flags/hk.png'),
        alpha2Code: 'HK',
        callingCode: '852',
        FIELD6: null,
    },
    {
        name: 'Hungary',
        name_ar: 'هنغاريا',
        flag: require('../../assets/flags/hu.png'),
        alpha2Code: 'HU',
        callingCode: '36',
        FIELD6: null,
    },
    {
        name: 'Iceland',
        name_ar: 'أيسلندا',
        flag: require('../../assets/flags/is.png'),
        alpha2Code: 'IS',
        callingCode: '354',
        FIELD6: null,
    },
    {
        name: 'India',
        name_ar: 'الهند',
        flag: require('../../assets/flags/in.png'),
        alpha2Code: 'IN',
        callingCode: '91',
        FIELD6: null,
    },
    {
        name: 'Indonesia',
        name_ar: 'إندونيسيا',
        flag: require('../../assets/flags/id.png'),
        alpha2Code: 'ID',
        callingCode: '62',
        FIELD6: null,
    },
    {
        name: 'Iran (Islamic Republic of)',
        name_ar: 'إيران (الجمهورية الإسلامية)',
        flag: require('../../assets/flags/ir.png'),
        alpha2Code: 'IR',
        callingCode: '98',
        FIELD6: null,
    },
    {
        name: 'Iraq',
        name_ar: 'العراق',
        flag: require('../../assets/flags/iq.png'),
        alpha2Code: 'IQ',
        callingCode: '964',
        FIELD6: null,
    },
    {
        name: 'Ireland',
        name_ar: 'أيرلندا',
        flag: require('../../assets/flags/ie.png'),
        alpha2Code: 'IE',
        callingCode: '353',
        FIELD6: null,
    },
    {
        name: 'Isle of Man',
        name_ar: 'جزيرة آيل أوف مان',
        flag: require('../../assets/flags/im.png'),
        alpha2Code: 'IM',
        callingCode: '44',
        FIELD6: null,
    },
    {
        name: 'Israel',
        name_ar: 'إسرائيل',
        flag: require('../../assets/flags/il.png'),
        alpha2Code: 'IL',
        callingCode: '972',
        FIELD6: null,
    },
    {
        name: 'Italy',
        name_ar: 'إيطاليا',
        flag: require('../../assets/flags/it.png'),
        alpha2Code: 'IT',
        callingCode: '39',
        FIELD6: null,
    },
    {
        name: 'Jamaica',
        name_ar: 'جامايكا',
        flag: require('../../assets/flags/jm.png'),
        alpha2Code: 'JM',
        callingCode: '1876',
        FIELD6: null,
    },
    {
        name: 'Japan',
        name_ar: 'اليابان',
        flag: require('../../assets/flags/jp.png'),
        alpha2Code: 'JP',
        callingCode: '81',
        FIELD6: null,
    },
    {
        name: 'Jersey',
        name_ar: 'جيرسي',
        flag: require('../../assets/flags/je.png'),
        alpha2Code: 'JE',
        callingCode: '44',
        FIELD6: null,
    },
    {
        name: 'Jordan',
        name_ar: 'الأردن',
        flag: require('../../assets/flags/jo.png'),
        alpha2Code: 'JO',
        callingCode: '962',
        FIELD6: null,
    },
    {
        name: 'Kazakhstan',
        name_ar: 'كازاخستان',
        flag: require('../../assets/flags/kz.png'),
        alpha2Code: 'KZ',
        callingCode: '76',
        FIELD6: null,
    },
    {
        name: 'Kenya',
        name_ar: 'كينيا',
        flag: require('../../assets/flags/ke.png'),
        alpha2Code: 'KE',
        callingCode: '254',
        FIELD6: null,
    },
    {
        name: 'Kiribati',
        name_ar: 'كيريباس',
        flag: require('../../assets/flags/ki.png'),
        alpha2Code: 'KI',
        callingCode: '686',
        FIELD6: null,
    },
    {
        name: "Korea (Democratic People's Republic of)",
        name_ar: 'كوريا، الجمهورية الشعبية الديمقراطية)',
        flag: require('../../assets/flags/kp.png'),
        alpha2Code: 'KP',
        callingCode: '850',
        FIELD6: null,
    },
    {
        name: 'Korea (Republic of)',
        name_ar: 'جمهورية كوريا)',
        flag: require('../../assets/flags/kr.png'),
        alpha2Code: 'KR',
        callingCode: '82',
        FIELD6: null,
    },
    {
        name: 'Kuwait',
        name_ar: 'الكويت',
        flag: require('../../assets/flags/kw.png'),
        alpha2Code: 'KW',
        callingCode: '965',
        FIELD6: null,
    },
    {
        name: 'Kyrgyzstan',
        name_ar: 'قرغيزستان',
        flag: require('../../assets/flags/kg.png'),
        alpha2Code: 'KG',
        callingCode: '996',
        FIELD6: null,
    },
    {
        name: "Lao People's Democratic Republic",
        name_ar: 'جمهورية لاو الديمقراطية الشعبية',
        flag: require('../../assets/flags/la.png'),
        alpha2Code: 'LA',
        callingCode: '856',
        FIELD6: null,
    },
    {
        name: 'Latvia',
        name_ar: 'لاتفيا',
        flag: require('../../assets/flags/lv.png'),
        alpha2Code: 'LV',
        callingCode: '371',
        FIELD6: null,
    },
    {
        name: 'Lebanon',
        name_ar: 'لبنان',
        flag: require('../../assets/flags/lb.png'),
        alpha2Code: 'LB',
        callingCode: '961',
        FIELD6: null,
    },
    {
        name: 'Lesotho',
        name_ar: 'ليسوتو',
        flag: require('../../assets/flags/ls.png'),
        alpha2Code: 'LS',
        callingCode: '266',
        FIELD6: null,
    },
    {
        name: 'Liberia',
        name_ar: 'ليبيريا',
        flag: require('../../assets/flags/lr.png'),
        alpha2Code: 'LR',
        callingCode: '231',
        FIELD6: null,
    },
    {
        name: 'Libya',
        name_ar: 'ليبيا',
        flag: require('../../assets/flags/ly.png'),
        alpha2Code: 'LY',
        callingCode: '218',
        FIELD6: null,
    },
    {
        name: 'Liechtenstein',
        name_ar: 'ليختنشتاين',
        flag: require('../../assets/flags/li.png'),
        alpha2Code: 'LI',
        callingCode: '423',
        FIELD6: null,
    },
    {
        name: 'Lithuania',
        name_ar: 'ليتوانيا',
        flag: require('../../assets/flags/lt.png'),
        alpha2Code: 'LT',
        callingCode: '370',
        FIELD6: null,
    },
    {
        name: 'Luxembourg',
        name_ar: 'لوكسمبورغ',
        flag: require('../../assets/flags/lu.png'),
        alpha2Code: 'LU',
        callingCode: '352',
        FIELD6: null,
    },
    {
        name: 'Macao',
        name_ar: 'ماكاو',
        flag: require('../../assets/flags/mo.png'),
        alpha2Code: 'MO',
        callingCode: '853',
        FIELD6: null,
    },
    {
        name: 'Macedonia (the former Yugoslav Republic of)',
        name_ar: 'مقدونيا (جمهورية اليوغوسلافية السابقة)',
        flag: require('../../assets/flags/mk.png'),
        alpha2Code: 'MK',
        callingCode: '389',
        FIELD6: null,
    },
    {
        name: 'Madagascar',
        name_ar: 'مدغشقر',
        flag: require('../../assets/flags/mg.png'),
        alpha2Code: 'MG',
        callingCode: '261',
        FIELD6: null,
    },
    {
        name: 'Malawi',
        name_ar: 'مالاوي',
        flag: require('../../assets/flags/mw.png'),
        alpha2Code: 'MW',
        callingCode: '265',
        FIELD6: null,
    },
    {
        name: 'Malaysia',
        name_ar: 'ماليزيا',
        flag: require('../../assets/flags/my.png'),
        alpha2Code: 'MY',
        callingCode: '60',
        FIELD6: null,
    },
    {
        name: 'Maldives',
        name_ar: 'جزر المالديف',
        flag: require('../../assets/flags/mv.png'),
        alpha2Code: 'MV',
        callingCode: '960',
        FIELD6: null,
    },
    {
        name: 'Mali',
        name_ar: 'مالي',
        flag: require('../../assets/flags/ml.png'),
        alpha2Code: 'ML',
        callingCode: '223',
        FIELD6: null,
    },
    {
        name: 'Malta',
        name_ar: 'مالطا',
        flag: require('../../assets/flags/mt.png'),
        alpha2Code: 'MT',
        callingCode: '356',
        FIELD6: null,
    },
    {
        name: 'Marshall Islands',
        name_ar: 'جزر مارشال',
        flag: require('../../assets/flags/mh.png'),
        alpha2Code: 'MH',
        callingCode: '692',
        FIELD6: null,
    },
    {
        name: 'Martinique',
        name_ar: 'مارتينيك',
        flag: require('../../assets/flags/mq.png'),
        alpha2Code: 'MQ',
        callingCode: '596',
        FIELD6: null,
    },
    {
        name: 'Mauritania',
        name_ar: 'موريتانيا',
        flag: require('../../assets/flags/mr.png'),
        alpha2Code: 'MR',
        callingCode: '222',
        FIELD6: null,
    },
    {
        name: 'Mauritius',
        name_ar: 'موريشيوس',
        flag: require('../../assets/flags/mu.png'),
        alpha2Code: 'MU',
        callingCode: '230',
        FIELD6: null,
    },
    {
        name: 'Mayotte',
        name_ar: 'مايوت',
        flag: require('../../assets/flags/yt.png'),
        alpha2Code: 'YT',
        callingCode: '262',
        FIELD6: null,
    },
    {
        name: 'Mexico',
        name_ar: 'المكسيك',
        flag: require('../../assets/flags/mx.png'),
        alpha2Code: 'MX',
        callingCode: '52',
        FIELD6: null,
    },
    {
        name: 'Micronesia (Federated States of)',
        name_ar: 'ميكرونيزيا (ولايات)',
        flag: require('../../assets/flags/fm.png'),
        alpha2Code: 'FM',
        callingCode: '691',
        FIELD6: null,
    },
    {
        name: 'Moldova (Republic of)',
        name_ar: 'جمهورية مولدوفا)',
        flag: require('../../assets/flags/md.png'),
        alpha2Code: 'MD',
        callingCode: '373',
        FIELD6: null,
    },
    {
        name: 'Monaco',
        name_ar: 'موناكو',
        flag: require('../../assets/flags/mc.png'),
        alpha2Code: 'MC',
        callingCode: '377',
        FIELD6: null,
    },
    {
        name: 'Mongolia',
        name_ar: 'منغوليا',
        flag: require('../../assets/flags/mn.png'),
        alpha2Code: 'MN',
        callingCode: '976',
        FIELD6: null,
    },
    {
        name: 'Montenegro',
        name_ar: 'الجبل الأسود',
        flag: require('../../assets/flags/me.png'),
        alpha2Code: 'ME',
        callingCode: '382',
        FIELD6: null,
    },
    {
        name: 'Montserrat',
        name_ar: 'مونتسيرات',
        flag: require('../../assets/flags/ms.png'),
        alpha2Code: 'MS',
        callingCode: '1664',
        FIELD6: null,
    },
    {
        name: 'Morocco',
        name_ar: 'المغرب',
        flag: require('../../assets/flags/ma.png'),
        alpha2Code: 'MA',
        callingCode: '212',
        FIELD6: null,
    },
    {
        name: 'Mozambique',
        name_ar: 'موزمبيق',
        flag: require('../../assets/flags/mz.png'),
        alpha2Code: 'MZ',
        callingCode: '258',
        FIELD6: null,
    },
    {
        name: 'Myanmar',
        name_ar: 'ميانمار',
        flag: require('../../assets/flags/mm.png'),
        alpha2Code: 'MM',
        callingCode: '95',
        FIELD6: null,
    },
    {
        name: 'Namibia',
        name_ar: 'ناميبيا',
        flag: require('../../assets/flags/na.png'),
        alpha2Code: 'NA',
        callingCode: '264',
        FIELD6: null,
    },
    {
        name: 'Nauru',
        name_ar: 'ناورو',
        flag: require('../../assets/flags/nr.png'),
        alpha2Code: 'NR',
        callingCode: '674',
        FIELD6: null,
    },
    {
        name: 'Nepal',
        name_ar: 'نيبال',
        flag: require('../../assets/flags/np.png'),
        alpha2Code: 'NP',
        callingCode: '977',
        FIELD6: null,
    },
    {
        name: 'Netherlands',
        name_ar: 'هولندا',
        flag: require('../../assets/flags/nl.png'),
        alpha2Code: 'NL',
        callingCode: '31',
        FIELD6: null,
    },
    {
        name: 'New Caledonia',
        name_ar: 'كاليدونيا الجديدة',
        flag: require('../../assets/flags/nc.png'),
        alpha2Code: 'NC',
        callingCode: '687',
        FIELD6: null,
    },
    {
        name: 'New Zealand',
        name_ar: 'نيوزيلاندا',
        flag: require('../../assets/flags/nz.png'),
        alpha2Code: 'NZ',
        callingCode: '64',
        FIELD6: null,
    },
    {
        name: 'Nicaragua',
        name_ar: 'نيكاراغوا',
        flag: require('../../assets/flags/ni.png'),
        alpha2Code: 'NI',
        callingCode: '505',
        FIELD6: null,
    },
    {
        name: 'Niger',
        name_ar: 'النيجر',
        flag: require('../../assets/flags/ne.png'),
        alpha2Code: 'NE',
        callingCode: '227',
        FIELD6: null,
    },
    {
        name: 'Nigeria',
        name_ar: 'نيجيريا',
        flag: require('../../assets/flags/ng.png'),
        alpha2Code: 'NG',
        callingCode: '234',
        FIELD6: null,
    },
    {
        name: 'Niue',
        name_ar: 'نيوي',
        flag: require('../../assets/flags/nu.png'),
        alpha2Code: 'NU',
        callingCode: '683',
        FIELD6: null,
    },
    {
        name: 'Norfolk Island',
        name_ar: 'جزيرة نورفولك',
        flag: require('../../assets/flags/nf.png'),
        alpha2Code: 'NF',
        callingCode: '672',
        FIELD6: null,
    },
    {
        name: 'Northern Mariana Islands',
        name_ar: 'جزر مريانا الشمالية',
        flag: require('../../assets/flags/mp.png'),
        alpha2Code: 'MP',
        callingCode: '1670',
        FIELD6: null,
    },
    {
        name: 'Norway',
        name_ar: 'النرويج',
        flag: require('../../assets/flags/no.png'),
        alpha2Code: 'NO',
        callingCode: '47',
        FIELD6: null,
    },
    {
        name: 'Oman',
        name_ar: 'سلطنة عمان',
        flag: require('../../assets/flags/om.png'),
        alpha2Code: 'OM',
        callingCode: '968',
        FIELD6: null,
    },
    {
        name: 'Pakistan',
        name_ar: 'باكستان',
        flag: require('../../assets/flags/pk.png'),
        alpha2Code: 'PK',
        callingCode: '92',
        FIELD6: null,
    },
    {
        name: 'Palau',
        name_ar: 'بالاو',
        flag: require('../../assets/flags/pw.png'),
        alpha2Code: 'PW',
        callingCode: '680',
        FIELD6: null,
    },
    {
        name: 'Palestine',
        name_ar: 'فلسطين',
        flag: require('../../assets/flags/ps.png'),
        alpha2Code: 'PS',
        callingCode: '970',
        FIELD6: 970,
    },
    {
        name: 'Panama',
        name_ar: 'بناما',
        flag: require('../../assets/flags/pa.png'),
        alpha2Code: 'PA',
        callingCode: '507',
        FIELD6: null,
    },
    {
        name: 'Papua New Guinea',
        name_ar: 'بابوا غينيا الجديدة',
        flag: require('../../assets/flags/pg.png'),
        alpha2Code: 'PG',
        callingCode: '675',
        FIELD6: null,
    },
    {
        name: 'Paraguay',
        name_ar: 'باراغواي',
        flag: require('../../assets/flags/py.png'),
        alpha2Code: 'PY',
        callingCode: '595',
        FIELD6: null,
    },
    {
        name: 'Peru',
        name_ar: 'بيرو',
        flag: require('../../assets/flags/pe.png'),
        alpha2Code: 'PE',
        callingCode: '51',
        FIELD6: null,
    },
    {
        name: 'Philippines',
        name_ar: 'فيلبيني',
        flag: require('../../assets/flags/ph.png'),
        alpha2Code: 'PH',
        callingCode: '63',
        FIELD6: null,
    },
    {
        name: 'Pitcairn',
        name_ar: 'بيتكيرن',
        flag: require('../../assets/flags/pn.png'),
        alpha2Code: 'PN',
        callingCode: '64',
        FIELD6: null,
    },
    {
        name: 'Poland',
        name_ar: 'بولندا',
        flag: require('../../assets/flags/pl.png'),
        alpha2Code: 'PL',
        callingCode: '48',
        FIELD6: null,
    },
    {
        name: 'Portugal',
        name_ar: 'البرتغال',
        flag: require('../../assets/flags/pt.png'),
        alpha2Code: 'PT',
        callingCode: '351',
        FIELD6: null,
    },
    {
        name: 'Puerto Rico',
        name_ar: 'بورتوريكو',
        flag: require('../../assets/flags/pr.png'),
        alpha2Code: 'PR',
        callingCode: '1787',
        FIELD6: null,
    },
    {
        name: 'Qatar',
        name_ar: 'دولة قطر',
        flag: require('../../assets/flags/qa.png'),
        alpha2Code: 'QA',
        callingCode: '974',
        FIELD6: null,
    },
    {
        name: 'Republic of Kosovo',
        name_ar: 'جمهورية كوسوو',
        flag: require('../../assets/flags/xk.png'),
        alpha2Code: 'XK',
        callingCode: '383',
        FIELD6: null,
    },
    {
        name: 'Romania',
        name_ar: 'رومانيا',
        flag: require('../../assets/flags/ro.png'),
        alpha2Code: 'RO',
        callingCode: '40',
        FIED6: null,
    },
    {
        name: 'Russian Federation',
        name_ar: 'الاتحاد الروي',
        flag: require('../../assets/flags/ru.png'),
        alpha2Code: 'RU',
        callingCode: '7',
        FIEL6: null,
    },
    {
        name: 'Rwanda',
        name_ar: 'رواندا',
        flag: require('../../assets/flags/rw.png'),
        alpha2Code: 'RW',
        callingCode: '250',
        FILD6: null,
    },
    {
        name: 'Réunion',
        name_ar: 'جمع شمل',
        flag: require('../../assets/flags/re.png'),
        alpha2Code: 'RE',
        callingCode: '262',
        FILD6: null,
    },
    {
        name: 'Saint Barthélemy',
        name_ar: 'سانت بارتيليمي',
        flag: require('../../assets/flags/bl.png'),
        alpha2Code: 'BL',
        callingCode: '590',
        FIELD6: null,
    },
    {
        name: 'Saint Helena',
        name_ar: 'سانت هيلانة',
        flag: require('../../assets/flags/sh.png'),
        alpha2Code: 'SH',
        callingCode: '290',
        FIELD6: 290,
    },
    {
        name: 'Saint Kitts and Nevis',
        name_ar: 'سانت كيتس ونيفيس',
        flag: require('../../assets/flags/kn.png'),
        alpha2Code: 'KN',
        callingCode: '1869',
        FIELD6: null,
    },
    {
        name: 'Saint Lucia',
        name_ar: 'القديسة لوسيا',
        flag: require('../../assets/flags/lc.png'),
        alpha2Code: 'LC',
        callingCode: '1758',
        FIELD6: null,
    },
    {
        name: 'Saint Martin (French part)',
        name_ar: 'سانت مارتن (الجزء الفرنسي)',
        flag: require('../../assets/flags/mf.png'),
        alpha2Code: 'MF',
        callingCode: '590',
        FIELD6: null,
    },
    {
        name: 'Saint Pierre and Miquelon',
        name_ar: 'سانت بيير وميكلون',
        flag: require('../../assets/flags/pm.png'),
        alpha2Code: 'PM',
        callingCode: '508',
        FIELD6: null,
    },
    {
        name: 'Saint Vincent and the Grenadines',
        name_ar: 'سانت فنسنت وجزر غرينادين',
        flag: require('../../assets/flags/vc.png'),
        alpha2Code: 'VC',
        callingCode: '1784',
        FIELD6: null,
    },
    {
        name: 'Samoa',
        name_ar: 'ساموا',
        flag: require('../../assets/flags/ws.png'),
        alpha2Code: 'WS',
        callingCode: '685',
        FIELD6: null,
    },
    {
        name: 'San Marino',
        name_ar: 'سان مارينو',
        flag: require('../../assets/flags/sm.png'),
        alpha2Code: 'SM',
        callingCode: '378',
        FIELD6: null,
    },
    {
        name: 'Sao Tome and Principe',
        name_ar: 'ساو تومي وبرينسيبي',
        flag: require('../../assets/flags/st.png'),
        alpha2Code: 'ST',
        callingCode: '239',
        FIELD6: null,
    },
    {
        name: 'Senegal',
        name_ar: 'السنغال',
        flag: require('../../assets/flags/sn.png'),
        alpha2Code: 'SN',
        callingCode: '221',
        FIELD6: null,
    },
    {
        name: 'Serbia',
        name_ar: 'صربيا',
        flag: require('../../assets/flags/rs.png'),
        alpha2Code: 'RS',
        callingCode: '381',
        FILD6: null,
    },
    {
        name: 'Seychelles',
        name_ar: 'سيشيل',
        flag: require('../../assets/flags/sc.png'),
        alpha2Code: 'SC',
        callingCode: '248',
        FIELD6: null,
    },
    {
        name: 'Sierra Leone',
        name_ar: 'سيرا ليون',
        flag: require('../../assets/flags/sl.png'),
        alpha2Code: 'SL',
        callingCode: '232',
        FIELD6: null,
    },
    {
        name: 'Singapore',
        name_ar: 'سنغافورة',
        flag: require('../../assets/flags/sg.png'),
        alpha2Code: 'SG',
        callingCode: '65',
        FIELD6: null,
    },
    {
        name: 'Sint Maarten (Dutch part)',
        name_ar: 'سانت مارتن (الجزء الهولندي)',
        flag: require('../../assets/flags/sx.png'),
        alpha2Code: 'SX',
        callingCode: '1721',
        FIELD6: null,
    },
    {
        name: 'Slovakia',
        name_ar: 'سلوفاكيا',
        flag: require('../../assets/flags/sk.png'),
        alpha2Code: 'SK',
        callingCode: '421',
        FIELD6: null,
    },
    {
        name: 'Slovenia',
        name_ar: 'سلوفينيا',
        flag: require('../../assets/flags/si.png'),
        alpha2Code: 'SI',
        callingCode: '386',
        FIELD6: null,
    },
    {
        name: 'Solomon Islands',
        name_ar: 'جزر سليمان',
        flag: require('../../assets/flags/sb.png'),
        alpha2Code: 'SB',
        callingCode: '677',
        FIELD6: null,
    },
    {
        name: 'Somalia',
        name_ar: 'الصومال',
        flag: require('../../assets/flags/so.png'),
        alpha2Code: 'SO',
        callingCode: '252',
        FIELD6: null,
    },
    {
        name: 'South Africa',
        name_ar: 'جنوب أفريقيا',
        flag: require('../../assets/flags/za.png'),
        alpha2Code: 'ZA',
        callingCode: '27',
        FIELD6: null,
    },
    {
        name: 'South Georgia and the South Sandwich Islands',
        name_ar: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية',
        flag: require('../../assets/flags/gs.png'),
        alpha2Code: 'GS',
        callingCode: '500',
        FIELD6: null,
    },
    {
        name: 'South Sudan',
        name_ar: 'جنوب السودان',
        flag: require('../../assets/flags/ss.png'),
        alpha2Code: 'SS',
        callingCode: '211',
        FIELD6: null,
    },
    {
        name: 'Spain',
        name_ar: 'إسبانيا',
        flag: require('../../assets/flags/es.png'),
        alpha2Code: 'ES',
        callingCode: '34',
        FIELD6: null,
    },
    {
        name: 'Sri Lanka',
        name_ar: 'سيريلانكا',
        flag: require('../../assets/flags/lk.png'),
        alpha2Code: 'LK',
        callingCode: '94',
        FIELD6: null,
    },
    {
        name: 'Sudan',
        name_ar: 'السودان',
        flag: require('../../assets/flags/sd.png'),
        alpha2Code: 'SD',
        callingCode: '249',
        FIELD6: null,
    },
    {
        name: 'Suriname',
        name_ar: 'سورينام',
        flag: require('../../assets/flags/sr.png'),
        alpha2Code: 'SR',
        callingCode: '597',
        FIELD6: null,
    },
    {
        name: 'Svalbard and Jan Mayen',
        name_ar: 'سفالبارد وجان مايان',
        flag: require('../../assets/flags/sj.png'),
        alpha2Code: 'SJ',
        callingCode: '4779',
        FIELD6: null,
    },
    {
        name: 'Swaziland',
        name_ar: 'سوازيلاند',
        flag: require('../../assets/flags/sz.png'),
        alpha2Code: 'SZ',
        callingCode: '268',
        FIELD6: null,
    },
    {
        name: 'Sweden',
        name_ar: 'السويد',
        flag: require('../../assets/flags/se.png'),
        alpha2Code: 'SE',
        callingCode: '46',
        FIELD6: null,
    },
    {
        name: 'Switzerland',
        name_ar: 'سويسرا',
        flag: require('../../assets/flags/ch.png'),
        alpha2Code: 'CH',
        callingCode: '41',
        FIELD6: null,
    },
    {
        name: 'Syrian Arab Republic',
        name_ar: 'الجمهورية العربية السورية',
        flag: require('../../assets/flags/sy.png'),
        alpha2Code: 'SY',
        callingCode: '963',
        FIELD6: null,
    },
    {
        name: 'Taiwan',
        name_ar: 'تايوان',
        flag: require('../../assets/flags/tw.png'),
        alpha2Code: 'TW',
        callingCode: '886',
        FIELD6: null,
    },
    {
        name: 'Tajikistan',
        name_ar: 'طاجيكستان',
        flag: require('../../assets/flags/tj.png'),
        alpha2Code: 'TJ',
        callingCode: '992',
        FIELD6: null,
    },
    {
        name: 'Tanzania',
        name_ar: 'تنزانيا',
        flag: require('../../assets/flags/tz.png'),
        alpha2Code: 'TZ',
        callingCode: '255',
        FIELD6: 255,
    },
    {
        name: 'Thailand',
        name_ar: 'تايلاند',
        flag: require('../../assets/flags/th.png'),
        alpha2Code: 'TH',
        callingCode: '66',
        FIELD6: null,
    },
    {
        name: 'Timor-Leste',
        name_ar: 'تيمور الشرقية',
        flag: require('../../assets/flags/tl.png'),
        alpha2Code: 'TL',
        callingCode: '670',
        FIELD6: null,
    },
    {
        name: 'Togo',
        name_ar: 'توجو',
        flag: require('../../assets/flags/tg.png'),
        alpha2Code: 'TG',
        callingCode: '228',
        FIELD6: null,
    },
    {
        name: 'Tokelau',
        name_ar: 'توكيلاو',
        flag: require('../../assets/flags/tk.png'),
        alpha2Code: 'TK',
        callingCode: '690',
        FIELD6: null,
    },
    {
        name: 'Tonga',
        name_ar: 'تونغا',
        flag: require('../../assets/flags/to.png'),
        alpha2Code: 'TO',
        callingCode: '676',
        FIELD6: null,
    },
    {
        name: 'Trinidad and Tobago',
        name_ar: 'ترينداد وتوباغو',
        flag: require('../../assets/flags/tt.png'),
        alpha2Code: 'TT',
        callingCode: '1868',
        FIELD6: null,
    },
    {
        name: 'Tunisia',
        name_ar: 'تونس',
        flag: require('../../assets/flags/tn.png'),
        alpha2Code: 'TN',
        callingCode: '216',
        FIELD6: null,
    },
    {
        name: 'Turkey',
        name_ar: 'ديك رومى',
        flag: require('../../assets/flags/tr.png'),
        alpha2Code: 'TR',
        callingCode: '90',
        FIELD6: null,
    },
    {
        name: 'Turkmenistan',
        name_ar: 'تركمانستان',
        flag: require('../../assets/flags/tm.png'),
        alpha2Code: 'TM',
        callingCode: '993',
        FIELD6: null,
    },
    {
        name: 'Turks and Caicos Islands',
        name_ar: 'جزر تركس وكايكوس',
        flag: require('../../assets/flags/tc.png'),
        alpha2Code: 'TC',
        callingCode: '1649',
        FIELD6: null,
    },
    {
        name: 'Tuvalu',
        name_ar: 'توفالو',
        flag: require('../../assets/flags/tv.png'),
        alpha2Code: 'TV',
        callingCode: '688',
        FIELD6: null,
    },
    {
        name: 'Uganda',
        name_ar: 'أوغندا',
        flag: require('../../assets/flags/ug.png'),
        alpha2Code: 'UG',
        callingCode: '256',
        FIELD6: null,
    },
    {
        name: 'Ukraine',
        name_ar: 'أوكرانيا',
        flag: require('../../assets/flags/ua.png'),
        alpha2Code: 'UA',
        callingCode: '380',
        FIELD6: null,
    },
    {
        name: 'United Kingdom of Great Britain and Northern Ireland',
        name_ar: 'المملكة المتحدة لبريطانيا العظمى وأيرلندا الشمالية',
        flag: require('../../assets/flags/gb.png'),
        alpha2Code: 'GB',
        callingCode: '44',
        FIELD6: null,
    },
    {
        name: 'United States of America',
        name_ar: 'الولايات المتحدة',
        flag: require('../../assets/flags/us.png'),
        alpha2Code: 'US',
        callingCode: '1',
        FIELD6: null,
    },
    {
        name: 'Uruguay',
        name_ar: 'أوروغواي',
        flag: require('../../assets/flags/uy.png'),
        alpha2Code: 'UY',
        callingCode: '598',
        FIELD6: null,
    },
    {
        name: 'Uzbekistan',
        name_ar: 'أوزبكستان',
        flag: require('../../assets/flags/uz.png'),
        alpha2Code: 'UZ',
        callingCode: '998',
        FIELD6: null,
    },
    {
        name: 'Vanuatu',
        name_ar: 'فانواتو',
        flag: require('../../assets/flags/vu.png'),
        alpha2Code: 'VU',
        callingCode: '678',
        FIELD6: null,
    },
    {
        name: 'Venezuela (Bolivarian Republic of)',
        name_ar: 'فنزويلا (الجمهورية البوليفارية)',
        flag: require('../../assets/flags/ve.png'),
        alpha2Code: 'VE',
        callingCode: '58',
        FIELD6: null,
    },
    {
        name: 'Viet Nam',
        name_ar: 'فيتنام',
        flag: require('../../assets/flags/vn.png'),
        alpha2Code: 'VN',
        callingCode: '84',
        FIELD6: null,
    },
    {
        name: 'Virgin Islands (British)',
        name_ar: 'جزر العذراء البريطانية)',
        flag: require('../../assets/flags/vg.png'),
        alpha2Code: 'VG',
        callingCode: '1284',
        FIELD6: null,
    },
    {
        name: 'Virgin Islands (U.S.)',
        name_ar: 'جزر العذراء (الولايات المتحدة)',
        flag: require('../../assets/flags/vi.png'),
        alpha2Code: 'VI',
        callingCode: '1 340',
        FIELD6: null,
    },
    {
        name: 'Wallis and Futuna',
        name_ar: 'واليس وفوتونا',
        flag: require('../../assets/flags/wf.png'),
        alpha2Code: 'WF',
        callingCode: '681',
        FIELD6: null,
    },
    {
        name: 'Western Sahara',
        name_ar: 'الصحراء الغربية',
        flag: require('../../assets/flags/eh.png'),
        alpha2Code: 'EH',
        callingCode: '212',
        FIELD6: null,
    },
    {
        name: 'Yemen',
        name_ar: 'اليمن',
        flag: require('../../assets/flags/ye.png'),
        alpha2Code: 'YE',
        callingCode: '967',
        FIELD6: null,
    },
    {
        name: 'Zambia',
        name_ar: 'زامبيا',
        flag: require('../../assets/flags/zm.png'),
        alpha2Code: 'ZM',
        callingCode: '260',
        FIELD6: null,
    },
    {
        name: 'Zimbabwe',
        name_ar: 'زيمبابوي',
        flag: require('../../assets/flags/zw.png'),
        alpha2Code: 'ZW',
        callingCode: '263',
        FIELD6: null,
    },
    {
        name: 'Åland Islands',
        name_ar: 'جزر آلاند',
        flag: require('../../assets/flags/ax.png'),
        alpha2Code: 'AX',
        callingCode: '358',
        FIELD6: null,
    },
];
